on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      BranchToDeploy:
        description: 'Select which branch to get deployed'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - staging
        
jobs:
  prJob:    
    name: Print info
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event_name }}"
          echo "${{ inputs.BranchToDeploy }}"
      - name: ToDeploy
        id: ToDeploy
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "BranchName=main" >> $GITHUB_OUTPUT
          else
            echo "BranchName=${{inputs.BranchToDeploy}}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout Repo
        uses: actions/checkout@v4
        with: 
          ref: ${{ steps.ToDeploy.outputs.BranchName }}
      - name: Check Branch
        run: |
          git branch
